import Header from "@/components/Header"
import LotteryEntrance from "@/components/LotteryEntrance"
import Head from "next/head"

export default function Home() {
    return (
        <>
            <Head>
                <title>Hardhat Raffle</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Header />
                <LotteryEntrance />
            </main>
        </>
    )
}
